export const firstElement = 0;
export const step = 1;
export const defaultVolume = 0.5;
export const maxPercentage = 100;
export const defaultVolumePercent = defaultVolume * maxPercentage;
export const debounceLoadingState = 200;
export const truncateBackStackQueue = 65536;
export const offsetTimeBumpToStart = 5;
export const metadataBytesLength = 3072;
